### PR TITLE
Add area-coords attribute

### PR DESCRIPTION
**Pull request by mpolichette**
I've implemented setting coordinates on the scope using an 'area-coords' attribute as I described in https://github.com/alexk111/ngImgCrop/issues/4

### CODE REVIEW

**Comment by cspeer** [comment]
Please, can we get this merged? :)

**Comment by PR-O** [comment]
Same here. Merging this would enable us to enjoy ngImgCrop even more ;)!

**Comment by Javarome** [comment]
For those interested, I've forked the repo to add the expected feature at https://github.com/Javarome/ngImgCrop
See demo at http://codepen.io/Javarome/pen/RPLZvd

**Comment by valera33** [comment]
Any chance to see it merged?

**Comment by Javarome** [comment]
Could be, but it looks that this project is not managed anymore.

**Comment by MaximilianLloyd** [comment]
So annoying when a decently sized project gets abandoned and the owner does not give anyone ownership of the repo.

**Pull request closed without merging**
